### ISSUE TITLE
Couldn't connect to host

### ISSUE THREAD

**Issue by rjcristy** [ParsePlatform/parse-php-sdk#256]
$parseApp_id = '7AJxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    $parseRestkey_id = 'tEpHnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    $parseMasterkey_id = 'EhXgxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
	
    $serverURL = 'http://192.241.139.144:1337';
    $parshhhhh = 'parse';

    ParseClient::initialize($parseApp_id, $parseRestkey_id, $parseMasterkey_id);
    ParseClient::setServerURL($serverURL, $parshhhhh);
    $postEmail 	= $_POST["email"];

    $s_query = new ParseQuery("_User");
    $s_query->equalTo("email", $postEmail);
    $user = $s_query->first();

It says

    <br />
    <b>Fatal error</b>:  Uncaught exception 'Parse\ParseException' with message 'couldn't connect to host' in /home4/****/public_html/****/src/Parse/ParseClient.php:363

Haven't seen any solution so far..

**Comment by rjcristy** [comment]
It seems I need to set the port 1337 to 80 .

**Comment by djdannycastillo** [comment]
I have the same problem. In the localhost work fine but in my server not work. How do I solve it?

**Comment by montymxb** [comment]
@djdannycastillo sounds like you have another issue, as the solution was detailed above. But, with that said it could be similar? The error from above mentions the host cannot be reached, so for starters try reaching the host from your server machine using telnet or something else to verify the host is up and the port is reachable, such as:
```shell
telnet my.parse-server.com 1337
```
If you can't connect then it's either an alternate port (some parse servers could use 80 instead of 1337, or perhaps another port still) or the host you're trying to reach is not up.

Check for a typo in your ```ParseClient::setServerURL``` call. Say the url to reach your server is
```
https://my.parse-server.com:1337/parse
```
You would call as follows
```php
ParseClient::setServerURL("https://my.parse-server.com:1337", "parse");
```
Beyond that, to solve this (and future issues) you need to approach this as a scientist. Form a hypothesis, put together a series of tests to run, collect the evidence and draw conclusions based on the results (put simply). 

If you are having an issue with connecting and you think the host is not down, prove it to yourself. Test and figure out if it's up. If you can verify it's up you can draw further conclusions and make additional hypothesis. Maybe your parse server is down but the host is up, or maybe the url you are connecting to is incorrect. 

Keep testing and moving along until you have isolated the cause of the issue you're observing. If, after all this you're still stuck at least you will have sufficient information based on your conclusions for others (like myself) to scrutinize and give actionable feedback on 👍 .
