### ISSUE TITLE
PHP SDK v 1.2.1 giving unauthorized on any requests after initialization

### ISSUE THREAD

**Issue by jakelisby** [ParsePlatform/parse-php-sdk#271]
I'm running Parse Server 2.2.24 and when trying to connect using the PHP SDK, all my requests are returning an "unauthorized" response. Note, everything functions correctly for the iOS and Rest connections. In addition, the Parse Dashboard v 1.0.19 works correctly as well. 

My initialization looks like this:
```
ParseClient::initialize('APP_ID', 'REST_KEY', 'MASTER_KEY');
ParseClient::setServerURL('https://parseapi.back4app.com', '/');
```

and my actual call looks like this:
```
try {
    $query = new ParseQuery("TestObject");
    $results = $query->find($useMasterKey = true); // <-- use master key!!
    echo count($results);

  } catch (\Exception $e) {
    echo $e->getMessage();
  }
```

I tried running the request with both $useMasterKey and without. Are there any special things I need to be doing to make this work? I have the SDK installed and included using via composer.

**Comment by gateway** [comment]
Few questions what is the path in your index.js or config for parse server?

```
// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
```

Because you have ParseClient::setServerURL('https://parseapi.back4app.com', '/');  where / wouldn't hit the mountpath.

The query you also have is not valid, do you have a real world example of what your trying to do?

Then lastly have you enabled VERBOSE = 1 on the server and looked at the logs for more information as to what might be going on.

**Comment by montymxb** [comment]
Your call to ```ParseClient::setServerURL``` looks correct for back4app.com, you can check this against the exception resolved in #267 .

 As for the 'unauthorized' response, I'm not too sure. However it would be prudent to mention that again in #267 it was found the back4app api has a compatibility issue with the Parse PHP SDK regarding errors. I can't tell whether you're experiencing the <i>same</i> bug, but it remains unresolved in the current sdk. It might be worth applying the patch mentioned in #267  and see if that helps at all, since the pull request containing the fix is still pending.

If that doesn't resolve your issue perhaps you could post up a bit of the response you're getting, might help us further narrow down what your problem is.

**Comment by gateway** [comment]
ahh, Ok I missed the whole back to app thing, so not sure how they do things.  I was just trying to reply as a basic here is how things should work :)

**Comment by jakelisby** [comment]
I implemented the patch, and no avail. It's also worth noting that CURL is working fine as well with this configuration, so it must be something the PHP SDK doesn't like...

I'm using the Slim framework, so here's the response I'm getting on the app side:

```
#0 /Users/jakelisby/Dropbox/Sweets/sweetsapp.com/vendor/parse/php-sdk/src/Parse/ParseQuery.php(378): Parse\ParseClient::_request('GET', 'classes/Groups?...', NULL, NULL, false)
#1 /Users/jakelisby/Dropbox/Sweets/sweetsapp.com/vendor/parse/php-sdk/src/Parse/ParseQuery.php(306): Parse\ParseQuery->find(false)
#2 /Users/jakelisby/Dropbox/Sweets/sweetsapp.com/vendor/parse/php-sdk/src/Parse/ParseQuery.php(93): Parse\ParseQuery->first(false)
#3 /Users/jakelisby/Dropbox/Sweets/sweetsapp.com/controllers/unit_test.php(1041): Parse\ParseQuery->get('63kQG9Tfwh')
#4 [internal function]: {closure}()
```

And the exception:
```
Type: Parse\ParseException
Message: unauthorized
File: /Users/jakelisby/Dropbox/Sweets/sweetsapp.com/vendor/parse/php-sdk/src/Parse/ParseClient.php
Line: 370
```

When working with the Back4App support, they said there are 403 errors, but no 401s in the logs. 

I appreciate any help in getting this resolved!

**Comment by gateway** [comment]
@jakelisby So you said this worked fine in 2.2.23? They did add more security in 2.2.24 fyi.

**Comment by jakelisby** [comment]
@gateway no, it hasn't ever connected. I am able to connect to the Parse API using the current PHP SDK, but I have consistently gotten an 'unauthorized' error when trying to connect to parseapi.back4app.com

**Comment by montymxb** [comment]
@jakelisby  Taking a look at the trace you posted there are a few things that come to mind.

For starters it looks like your call to ```#0... Parse\ParseClient::_request('GET', 'classes/Groups?...', NULL, NULL, false)``` is not passing a a session token (the third parameter) in the request. If your 'Groups' class has a class ACL that prevents public reading or the object you are attempting to get is not publicly accessible, you could be denied (assuming you are not logged in as a user before hand). If you think there might be an issue with a user not staying logged in or otherwise persisting you can always check 
```php
$user = ParseUser::getCurrentUser();
```
If you want to check for that session token you can additionally call
```php
$token = $user->getSessionToken();
```
Again, this is assuming you need to be logged in before you read these objects, if they're publicly readable you can ignore all that.

Another thing is in the exception you mentioned
```
Message: unauthorized
File: .../ParseClient.php
Line: 370
```
Checking around in the SDK doesn't seem to show any message of 'unauthorized', so it's probably something coming from the server. Going to line 370 in ParseClient we find this
```php
curl_close($rest);
if (strpos($contentType, 'text/html') !== false) {
    throw new ParseException('Bad Request', -1);
}
```
Where the exception being thrown is on line 370. This is thrown when the return type is text/html instead of the expected JSON return type. If the file on your end has the same code at the same lines it would seem that the issue is coming from here, at least from what the exception says. Furthermore, if you're curious about what is actually coming back from back4app.com, you can check the actual response itself. If back4app mentioned they were seeing 403s in the logs you might be getting a 403 html file instead of the expected JSON return value.

Finally (and you may have already done but it's worth mentioning) double check that you're setting up a PHP Session via ```session_start()``` before you initialize the php sdk. Internally, if no session is setup, the sdk will resort to using in memory storage. This works until you load another page, where it's as if you never logged in.

Hopefully this will get you a bit closer to resolving your issue, let us know what you find!

**Comment by jakelisby** [comment]
Just wanted to follow up to close this one out. My issue had resulted from initializing the connection to back4app and then later (in a random spot in my code) reinitializing in an attempt back to the old Parse.com api. Davi and his team over at back4app helped me track down the issue and now I'm off to the races. Thanks everyone on this thread for your help as well!
