### ISSUE TITLE
MasterKey is ignored 

### ISSUE THREAD

**Issue by Cliffordwh** [ParsePlatform/parse-php-sdk#275]
Can confirm that masterKey on initialization is ignored. 

```
 ParseClient::initialize('YOUR_APP_ID', 'REST_KEY', 'YOUR_MASTER_KEY');
 ParseClient::setServerURL('http://YOUR_PARSE_SERVER:1337/parse');
```

**Comment by montymxb** [comment]
If you take a look in ```ParseClient::initialize``` the master key is stored in the static var ```$masterKey```. This is used in ```ParseClient::_getRequestHeaders``` (when master key use is requested) to provide the ```X-Parse-Master-Key``` header with the master key as the value. 

The master key is definitely used, but it depends on the request. If ```$useMasterKey``` is false for a given request in ```ParseClient::_request``` (the default value is false as well) the master key will not be added to the request headers. In such a case the master key will not be used, but this is expected behavior.

Let me know if this clears things up on your end or if you're having a more specific issue so we can help you out.
