### ISSUE TITLE
updating parse php

### ISSUE THREAD

**Issue by jopaulam** [ParsePlatform/parse-php-sdk#282]
when i finished following the guide, i encountered this problem......

Fatal error: Uncaught exception 'Parse\ParseException' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\BCM2\src\Parse\ParseClient.php:381 Stack trace: #0 C:\xampp\htdocs\BCM2\src\Parse\ParseQuery.php(378): Parse\ParseClient::_request('GET', 'classes/notific...', NULL, NULL, false) #1 C:\xampp\htdocs\BCM2\uppush.php(38): Parse\ParseQuery->find() #2 {main} thrown in C:\xampp\htdocs\BCM2\src\Parse\ParseClient.php on line 381

what did i miss?

**Comment by montymxb** [comment]
@jopaulam This is not an issue with the sdk but rather your local setup. You have an issue with your XAMPP installation, specifically regarding your issuer certificate as the error says. [Try this](https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate#32095378), it's an SO post which appears to be specific enough to fix your issue of having an out of date certificate authority bundle.

**Comment by jopaulam** [comment]
@montymxb thanks, i encountered another problem.........

Fatal error: Uncaught exception 'Parse\ParseException' with message 'Missing push configuration' in C:\xampp\htdocs\BCM2\src\Parse\ParseClient.php:406 Stack trace: #0 C:\xampp\htdocs\BCM2\src\Parse\ParsePush.php(78): Parse\ParseClient::_request('POST', 'push', NULL, '{"channels":["E...', true, false, 'application/jso...', true) #1 C:\xampp\htdocs\BCM2\push1.php(27): Parse\ParsePush::send(Array, true) #2 {main} thrown in C:\xampp\htdocs\BCM2\src\Parse\ParseClient.php on line 406

again what did i miss?

**Comment by montymxb** [comment]
@jopaulam Looks like your Parse Server instance is missing a [push configuration](https://parseplatform.github.io/docs/parse-server/guide/#push-notifications). You'll need setup GCM and APNS in order to reach Android and iOS devices respectively (or whichever one you need). The link should detail what you need to get started with that.

Also we recently added a ```ParsePushStatus``` class for getting feedback from pushes, should be rather nifty. The usage is updated on the [front page](https://github.com/ParsePlatform/parse-php-sdk/).

**Comment by jopaulam** [comment]
i have used the class but encountered this

Fatal error: Uncaught exception 'Parse\ParseException' with message 'Sending a push requires either "channels" or a "where" query.'
   
i used this

$data = array("alert" => $message1);

// Parse Server requires the master key for sending push.  Pass true as the second parameter.
ParsePush::send($data, true);

// Push to Channels
$try = ParsePush::send(array(
  "channels" => (['Everyone']),
  "data" => $data
), true);

// Push to Query
$query = ParseInstallation::query();
$query->equalTo("message", "date");

ParsePush::send(array(
    "where" => $query,
    "data" => $data
), true);

**Comment by montymxb** [comment]
@jopaulam turns out that ParseServer requires either a channel _or_ a query, but not both. I'll be updating this in the README and adding test cases as well to account for this.

In your usage above, which you pulled from the README, you'll want to update ```ParsePush::send($data, true);``` to use a query/channel like the examples below, but be sure not to use both otherwise you'll get another error as well.

For future reference when you have an error can you provide further details as to where the error occurred, i.e. line # and actual lines involved. Providing details regarding issues you encounter (especially the circumstances that cause it) will help us to identify and quickly resolve problems in the future. It's greatly appreciated when a detailed analysis of your problem is provided.

**Comment by jopaulam** [comment]
i have used pushed to channel part in the README, i still recieve this

Fatal error: Uncaught exception 'Parse\ParseException' with message 'Sending a push requires either "channels" or a "where" query.' in C:\xampp\htdocs\BCM2\src\Parse\ParseClient.php:410 Stack trace: #0 C:\xampp\htdocs\BCM2\src\Parse\ParsePush.php(78): Parse\ParseClient::_request('POST', 'push', NULL, '{"alert":""}', true, false, 'application/jso...', true) #1 C:\xampp\htdocs\BCM2\push1.php(23): Parse\ParsePush::send(Array, true) #2 {main} thrown in C:\xampp\htdocs\BCM2\src\Parse\ParseClient.php on line 410

i managed to fix other problems before this one bothered me......

**Comment by montymxb** [comment]
@jopaulam looks like you are still missing either a 'channels' or 'where' limit, it's pretty well defined that it must be one or the other. Unless you post up the code where you are making the call and provide a detailed stack trace we won't be able to help you out very much. All I can tell you from what you've provided is (and limited at best) that you missing what I mentioned above.

**Comment by jopaulam** [comment]
this is my code for push 

```php

require 'autoload.php';
use Parse\ParseClient;
use Parse\ParseUser;
use Parse\ParseObject;
use Parse\ParseACL;
use Parse\ParsePush;

$app_id = 'eh3c1o5Hk2Bx9lfWZ3ewMZl9njBVblwZF90WXRdB';
$rest_key = 'S2B9b31KNLghTVADvjTVS3yIKOiLMwrVhHjTHQbx';
$master_key  = 'kd0shk9udR3rmC8Ef31LptfYQpnlSTHojETC0lTK';

ParseClient::initialize( $app_id, $rest_key, $master_key );
ParseClient::setServerURL('https://parseapi.back4app.com', '/');

$message1 = $_POST['message'];
$date = $_POST['date'];

$data = array("alert" => $message1);

// Parse Server requires the master key for sending push.  Pass true as the second parameter.
ParsePush::send($data, true);

// Push to Channels
$try = ParsePush::send(array(
  "channels" => ["Everyone"],
  "data" => $data
), true);

// // Push to Query
// $query = ParseInstallation::query();
// $query->equalTo("message", "date");

// ParsePush::send(array(
//     "where" => $query,
//     "data" => $data
// ), true);

//Object
$object = ParseObject::create("notifications");
$objectId = $object->getObjectId();
$php = $object->get("message");

// Set values:
$object->set("message", $message1);
$object->set("date", $date);
$object->save();

```

and the part wheere the error referred to..
```php
$decoded = json_decode($response, true);
        if (isset($decoded['error'])) {
            // check to convert error to a string, if an array
            // used to handle an Array 'error' from back4app.com
            $errorMessage = is_array($decoded['error']) ? json_encode($decoded['error']) : $decoded['error'];
            **throw new ParseException(**
                $errorMessage,
                isset($decoded['code']) ? $decoded['code'] : 0
            );
        }
```

**Comment by montymxb** [comment]
The offending line looks to be here:
```php
// Parse Server requires the master key for sending push.  Pass true as the second parameter.
ParsePush::send($data, true);
```
In your first of 2 calls to ```ParsePush::send```. I'm assuming you copied that off the old README, the reference has since be updated. The issue here is that ```$data``` should not be passed on its own and should be passed with additional params. An example of a good call is in your second use of ```ParsePush::send```
```php
// Push to Channels
$try = ParsePush::send(array(
  "channels" => ["Everyone"],
  "data" => $data
), true);
```
There you are sending to a channel. You can also send using a 'where' parameter like in the lines below which you commented out.

You can remove the first call and ```$data``` will still be sent in the 2nd call to ```ParsePush::send``` (assuming you have people in the 'Everyone' channel, that should take care of it!

**Comment by jopaulam** [comment]
#78

**Comment by jopaulam** [comment]
i have updated the sdk and removed the first call `ParsePush::send($data, true);`, but sends me back to my first problem i posted...

**Comment by montymxb** [comment]
Hmm, well your client code looks ok now. I would double check as to how back4app handles push notifications.

You might try looking into [this doc @ back4app.com](https://docs.back4app.com/docs/parse-migration/push-notification/android-setting-up-push-notifications/) in regards to setting up push notifications for android. It will require some setup on your part for GCM, but once you have that in place you should be good. I believe they have a similar document for iOS, but I would expect you can find that if you need it. 

I would recommend you talk with back4app personnel in regards to issues related with Parse Server. They should be able to walk you through how to setup your account for handling pushes properly, and to handle any other issues as well. We did have another individual who worked with their support staff to successfully get their setup running.

**Comment by jopaulam** [comment]
@montymxb thank you for the help, finally got it working

**Comment by jopaulam** [comment]
http://github.com - automatic!
[GitHub](http://github.com)
