### ISSUE TITLE
Extending ParseUser

### ISSUE THREAD

**Issue by aruvalcaba** [ParsePlatform/parse-php-sdk#42]
Is this possible? I have tried for ParseObjects and that worked fine, for ParseUser no.

**Comment by HipsterJazzbo** [comment]
I'd really like this as well for a number of reasons:

1. I like to subclass so that I can docblock the subclasses and get property autocompletion/documentation
2. I'm using the repository pattern, and can't really do it very well without subclassing the built in `ParseUser` class
3. I like to add relationship methods to my subclasses, to ease retrieving children from the parent (get all the `Comment`s for a `Post` for example). Can't do that for users without subclassing.

Just my $0.02

**Comment by HipsterJazzbo** [comment]
@gfosco Found another fantastic reason to make this work: I'm building a package to integrate Parse pretty tightly with Laravel, and in order to do the authentication properly, I'll need this to extend the ParseUser object with a few more methods.

**Comment by HipsterJazzbo** [comment]
So I've just gone ahead and done this. I'll open a PR once you've merged #80, so that I don't have to rebase with the new PSR-2 code style.

**Comment by gfosco** [comment]
Closing this, it will be covered in #84.
