### ISSUE TITLE
fetch method does not offer master key support.

### ISSUE THREAD

**Issue by manojvelyalan** [ParsePlatform/parse-php-sdk#69]
Hi,
In my system admin need to change the status field of user in _User table.I tried to use below code but it is not updating and getting some warning.Here  current user is admin and trying to update other user info filed.

public function updateAdminComent($status = true,$comment,$objectID){
        
	$object = new \Parse\ParseObject("_User", $objectID);
	$object->fetch();
        $object->set('status',$status);
	$object->set("comment",strip_tags($comment));
	try {
            $object->save(true);
            return true;
	} catch (ParseException $ex) {

	return false;
	}

    }
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\src\Parse\ParseObject.php on line 532

**Comment by gfosco** [comment]
I believe this is occurring because you cannot fetch the user without the master key.  Your code above may work if you just remove the fetch call, since you're not using the information from the object (just setting data and saving.)  

Regardless, we should update this method to allow using the master key.

**Comment by gfosco** [comment]
I just pushed an update for this and tagged a release 1.0.5
